### ISSUE TITLE
Okay with forking?

### ISSUE THREAD

**Issue by simpixelated** [gor181/react-redux-mini-gallery#2]
Hey @gor181! You did such an awesome job with this component, I would like to include it in our app as a dependency. However, just to make it easier for me to maintain, I would prefer to fork it so that I can create the npm package and make updates directly. I would still give you credit in the list of authors and keep everything open source, with whatever license you would like. Does that sound ok to you?

**Comment by gor181** [comment]
Sure. Cheers
